### ISSUE TITLE
Bad Request (400) when when access http://127.0.0.1/

### ISSUE THREAD

**Issue by duchuyvp** [VNOI-Admin/vnoj-docker#1]
I did follow the instruction on README. When using a browser to access `localhost`, the server-site seems fine, but I had Bad Request (400) when access `http://127.0.0.1/` or an local IP address (`http://192.168.xx.xx`). I did some search and also tried to replace the line `ALLOWED_HOST = [HOST]` on `local_settings.py` with `ALLOWED_HOSTS = ['localhost', 'http://127.0.0.1/', '0.0.0.0']` but didn't work.

I need help!
Thank you.

**Comment by leduythuccs** [comment]
Please try ALLOWED_HOST = ['127.0.0.1'].

**Comment by duchuyvp** [comment]
Hi leduythuccs, thanks for your attention.
For example, when I tried `flask run --host=0.0.0.0`, the Flask app would run on all addresses which mention above. Is there a similar way for django app?

**Comment by leduythuccs** [comment]
`python3 manage.py runserver 0.0.0.0:80`.

But our docker doesn't run with runserver. We use uwsgi to run.

**Comment by leduythuccs** [comment]
Also, you need to set allowed host to accept `'*'`

**Comment by duchuyvp** [comment]
So, how to run with all addresses using uwsgi?

**Comment by leduythuccs** [comment]
im not sure, haven't tried it yet. Why do you want to run with `0.0.0.0` tho? The docker already config an nginx instance.

**Comment by duchuyvp** [comment]
I want to run the app in local network particularly. I was in class and my students should be able to access.

**Comment by leduythuccs** [comment]
Then you can config the nginx to accept `0.0.0.0` instead.

**Comment by leduythuccs** [comment]
```
listen       80  default_server;
    server_name  _;

```
More information: http://nginx.org/en/docs/http/server_names.html

**Comment by duchuyvp** [comment]
Thanks a lot a lot!!
I tried both `server_name  _;` on nginx config and `ALLOWED_HOSTS = ['*']` on local_settings.py  and it works pềct.
Have a nice day sir!
