### ISSUE TITLE
UI not response status automatically when submit.

### ISSUE THREAD

**Issue by dcwuy** [VNOI-Admin/vnoj-docker#2]
![image](https://user-images.githubusercontent.com/109254074/211983967-c4a08e5c-8de7-497e-84a6-8066cf5ab42d.png)
![image](https://user-images.githubusercontent.com/109254074/211984128-f2d8588f-6833-42a9-ab26-a2c5b30d3348.png)
I'm assuming that I having some problem with wsevent but I couldn't find out how to fix it. I found this issue https://github.com/DMOJ/online-judge/issues/924 but after trying all node versions from 12 to 19, it still didn't work.

**Comment by TienVN6222** [comment]
lỗi này mình cũng bị
![image](https://github.com/user-attachments/assets/ac083269-a1d1-4510-95ef-0437410b285a)
